version: '3.8'

services:
  bolhadev-chat:
    image: brunoroh/bolhadev-chat:latest
    build:
      dockerfile: ./docker/apps/Dockerfile
      args:
        PROJECT: server

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  nginx:
    build: ./docker/nginx/
    image: brunoroh/bolhadev-nginx:latest
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - bolhadev-chat

volumes:
  pgdata:
