import { GoogleAnalytics } from '@next/third-parties/google'
import "./globals.css";
import { GeistSans } from "geist/font/sans";
import type { Metadata } from "next";
import Image from "next/image";
import { Header } from "@/components/header";

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en" className={GeistSans.className}>
      <body className="dark flex h-screen flex-col ">
        <Header />
        <Image
          src="/light-ray.svg"
          alt="Purple light ray"
          width="1600"
          height="800"
          className="animate-in fade-in slide-in-from-bottom-1 absolute -z-10"
          style={{ color: "transparent", animationDuration: "10s" }}
        />
        <main className="h-full">{children}</main>
      </body>
      <GoogleAnalytics gaId="G-STY9BKWKT4" />
    </html>
  );
}
